FROM apache/airflow:2.9.1

USER root
RUN apt-get update && \
    apt-get install -y gcc build-essential && \
    apt-get clean

USER airflow

COPY airflow-requirements.txt /tmp/requirements.txt
RUN pip install --no-cache-dir -r /tmp/requirements.txt